### ISSUE TITLE
initial page disappears before clicked page loads

### ISSUE THREAD

**Issue by erisanolasheni** [imbolc/sapper-page-loading-bar#1]
Hello, this is a nice plugin and thanks.

However, it will be more cool to retain the initial page before the clicked page loads, or better, a configuration settings to select your preference, thanks.

**Comment by erisanolasheni** [comment]
Thanks, I was about to do this by removing the ```{#if !$preloading}``` condition in the _layout.svelte file.

**Comment by imbolc** [comment]
Sure :)
